# Generated by Django 5.1.5 on 2025-02-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='menbership',
            new_name='membership',
        ),
    ]
