# Generated by Django 5.1.5 on 2025-02-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_menbership_customer_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='places_at',
            new_name='placed_at',
        ),
    ]
