# Generated by Django 5.1.5 on 2025-02-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_places_at_order_placed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
