# Generated by Django 5.1.5 on 2025-02-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_storeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreUser',
        ),
    ]
