# Generated by Django 5.1.5 on 2025-02-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_storeuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='price',
        ),
    ]
